# Generated by Django 5.2.5 on 2025-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(help_text='Ex: 500g, 1L, 1U', max_length=100),
        ),
    ]
